import StaticPage from "../components/StaticPage";
import { footerHtml } from "../components/footerHtml";
import { productCategoryNavHtml } from "../components/productCategoryNav";
import { replaceProductsAllGridCards } from "../lib/productCards";
import { siteHeaderHtml } from "../components/siteHeaderHtml";


export const metadata = {
  title: "Custom Metal Products | Pins, Medals, Coins & Keychains",
  description: "Explore custom enamel pins, medals, challenge coins, keychains, buckles, golf accessories and other OEM metal gifts from Unique Pin.",
  alternates: {
    canonical: "/products",
  },
};

const html = String.raw`
  ${siteHeaderHtml({ active: "products" })}

  <main>
    <section class="page-hero products-page-hero">
      <div class="container about-hero-copy">
        <h1>Custom Metal Crafts</h1>
        <p>We specialize in custom enamel pins, medals, challenge coins, keychains and premium metal gifts. From original designs to mass production, we provide reliable OEM solutions for brands, distributors and organizations worldwide.</p>
      </div>
    </section>

    <section class="product-type-section products-all-section" id="all">
      <div class="container product-type-content">
        ${productCategoryNavHtml({ mode: "filter", active: "all", variant: "inline" })}
        <div class="product-type-grid products-all-grid">
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-yellow-character.jpg" alt="Yellow character hard enamel pin"><h2>Yellow Character Hard Enamel Pin</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-enamel-pins/yellow-character-hard-enamel-pin">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-auburn-proud.jpg" alt="Auburn Proud green soft enamel pin"><h2>Auburn Proud Soft Enamel Pin</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-enamel-pins/auburn-proud-soft-enamel-pin">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" id="pins" data-product-category="pins"><img src="assets/images/type-pins-soft-enamel.jpg" alt="Green character soft enamel pin set"><h2>Green Character Soft Enamel Pin Set</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-enamel-pins/green-character-soft-enamel-pin-set">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-hard-enamel.jpg" alt="Box cat and umbrella cat hard enamel pins"><h2>Box Cat and Umbrella Cat Enamel Pins</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-enamel-pins/box-cat-and-umbrella-cat-enamel-pins">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-die-struck.jpg" alt="Antique silver guitar crest enamel pin"><h2>Antique Silver Guitar Crest Enamel Pin</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-enamel-pins/antique-silver-guitar-crest-enamel-pin">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-printed.jpg" alt="Glitter tour truck printed enamel pin"><h2>Glitter Tour Truck Printed Enamel Pin</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-enamel-pins/glitter-tour-truck-printed-enamel-pin">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="coins" data-product-category="coins"><img src="assets/images/type-coins-3d.jpg" alt="3D antique firefighter challenge coins"><h2>3D Antique Firefighter Challenge Coins</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-challenge-coins/3d-antique-firefighter-challenge-coins">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="coins"><img src="assets/images/type-coins-double-sided.jpg" alt="Double sided anniversary challenge coin"><h2>Double Sided Anniversary Challenge Coin</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-challenge-coins/double-sided-anniversary-challenge-coin">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="coins"><img src="assets/images/type-coins-cut-shape.jpg" alt="Cut shape route map challenge coin"><h2>Cut Shape Route Map Challenge Coin</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-challenge-coins/cut-shape-route-map-challenge-coin">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="coins"><img src="assets/images/type-coins-antique.jpg" alt="Antique military squadron challenge coins"><h2>Antique Military Squadron Challenge Coins</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-challenge-coins/antique-military-squadron-challenge-coins">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="medals" data-product-category="medals"><img src="assets/images/type-medals-sports.png" alt="Silver basketball sports medal with ribbon"><h2>Silver Basketball Sports Medal with Ribbon</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-medals/silver-basketball-sports-medal-with-ribbon">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="medals"><img src="assets/images/type-medals-3d.png" alt="3D shield logo award medal"><h2>3D Shield Logo Award Medal</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-medals/3d-shield-logo-award-medal">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="medals"><img src="assets/images/type-medals-award.png" alt="Silver race award medal with ribbon"><h2>Silver Race Award Medal with Ribbon</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-medals/silver-race-award-medal-with-ribbon">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="medals"><img src="assets/images/type-medals-ribbon.png" alt="Blue marathon ribbon medal"><h2>Blue Marathon Ribbon Medal</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-medals/blue-marathon-ribbon-medal">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="keychains" data-product-category="keychains"><img src="assets/images/type-keychains-metal.jpg" alt="Colorful flower metal keychains"><h2>Colorful Flower Metal Keychains</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-metal-keychains/colorful-flower-metal-keychains">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="keychains"><img src="assets/images/type-keychains-enamel.jpg" alt="Palm island enamel keychain"><h2>Palm Island Enamel Keychain</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-metal-keychains/palm-island-enamel-keychain">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="keychains"><img src="assets/images/type-keychains-opener.jpg" alt="Round school logo keychain"><h2>Round School Logo Keychain</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-metal-keychains/round-school-logo-bottle-opener-keychain">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="keychains"><img src="assets/images/type-keychains-spinner.jpg" alt="Travel charm spinner keychain"><h2>Travel Charm Spinner Keychain</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-metal-keychains/travel-charm-spinner-keychain">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="buckles" data-product-category="buckles"><img src="assets/images/type-buckles-western.jpg" alt="Western skull relief belt buckle"><h2>Western Skull Relief Belt Buckle</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-belt-buckles/western-skull-relief-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="buckles"><img src="assets/images/type-buckles-logo.jpg" alt="Oval relief logo metal belt buckle"><h2>Oval Relief Logo Metal Belt Buckle</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-belt-buckles/oval-relief-logo-metal-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="buckles"><img src="assets/images/type-buckles-antique.jpg" alt="Antique silver rectangle logo belt buckle"><h2>Antique Silver Rectangle Logo Belt Buckle</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-belt-buckles/antique-silver-rectangle-logo-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="buckles"><img src="assets/images/type-buckles-enamel.jpg" alt="Oval club logo enamel belt buckle"><h2>Oval Club Logo Enamel Belt Buckle</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-belt-buckles/oval-club-logo-enamel-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="golf-accessories" data-product-category="golf-accessories"><img src="assets/images/type-golf-ball-marker.jpg" alt="Antique golf club divot tool ball marker"><h2>Antique Golf Club Divot Tool Ball Marker</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-golf-accessories/antique-golf-club-divot-tool-ball-marker">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="golf-accessories"><img src="assets/images/type-golf-hat-clip.jpg" alt="Avocado golf hat clip ball marker"><h2>Avocado Golf Hat Clip Ball Marker</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-golf-accessories/avocado-golf-hat-clip-ball-marker">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="golf-accessories"><img src="assets/images/type-golf-divot-tool.jpg" alt="Color logo golf divot tool set"><h2>Color Logo Golf Divot Tool Set</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-golf-accessories/color-logo-golf-divot-tool-set">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="bottle-openers" data-product-category="bottle-openers"><img src="assets/images/type-openers-coin.jpg" alt="Playing card metal bottle opener"><h2>Playing Card Metal Bottle Opener</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-bottle-openers/playing-card-metal-bottle-opener">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="bottle-openers"><img src="assets/images/type-openers-keychain.jpg" alt="Skull coin keychain bottle opener"><h2>Skull Coin Keychain Bottle Opener</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-bottle-openers/skull-coin-keychain-bottle-opener">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="cufflinks-tieclips" data-product-category="cufflinks-tieclips"><img src="assets/images/type-cufflinks-metal.jpg" alt="Blue carbon fiber metal cufflinks"><h2>Blue Carbon Fiber Metal Cufflinks</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-cufflinks-tie-clips/blue-carbon-fiber-metal-cufflinks">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="cufflinks-tieclips"><img src="assets/images/type-cufflinks-enamel.jpg" alt="Color plated metal tie clips"><h2>Color Plated Metal Tie Clips</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-cufflinks-tie-clips/color-plated-metal-tie-clips">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="cufflinks-tieclips"><img src="assets/images/type-tie-clips-logo.jpg" alt="Black skull logo cufflinks"><h2>Black Skull Logo Cufflinks</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-cufflinks-tie-clips/black-skull-logo-cufflinks">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="magnets" data-product-category="magnets"><img src="assets/images/type-magnets-enamel.png" alt="Ornate building enamel fridge magnet"><h2>Ornate Building Enamel Fridge Magnet</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-fridge-magnets/ornate-building-enamel-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="magnets"><img src="assets/images/type-magnets-3d.png" alt="Ferris wheel 3D metal fridge magnet"><h2>Ferris Wheel 3D Metal Fridge Magnet</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-fridge-magnets/ferris-wheel-3d-metal-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="magnets"><img src="assets/images/type-magnets-soft-pvc.png" alt="Cartoon character soft fridge magnet"><h2>Cartoon Character Soft Fridge Magnet</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-fridge-magnets/cartoon-character-soft-pvc-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="magnets"><img src="assets/images/type-magnets-souvenir.png" alt="City landmark souvenir fridge magnet"><h2>City Landmark Souvenir Fridge Magnet</h2><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="/products/custom-fridge-magnets/city-landmark-souvenir-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="/contact">GET QUOTE NOW</a></div></article>
        </div>
      </div>
    </section>

  </main>
  ${footerHtml}`;

export default function Page() {
  return <StaticPage html={replaceProductsAllGridCards(html)} />;
}
