import StaticPage from "../components/StaticPage";
import { productCategoryNavHtml } from "../components/productCategoryNav";

export const metadata = {
  title: "Custom Metal Products | Pins, Medals, Challenge Coins, Keychains & More",
  description: "Explore Unique Pin custom metal products including fridge magnets, enamel pins, medals, bottle openers, belt buckles, golf accessories, challenge coins, cufflinks, tie clips and keychains."
};

const html = String.raw`
  <div class="topbar"><div class="container"><span>Professional OEM/ODM Manufacturer Since 2003</span><span>Email: ceo@chinauniquepin.com | WhatsApp: +86 18895316838</span></div></div>
  <header class="site-header"><div class="container nav-wrap"><a class="brand" href="/"><img src="assets/images/logo.png" alt="Unique Pin logo"><span><strong>Unique Pin</strong><span>Custom Metal Gifts Factory</span></span></a><nav class="nav" aria-label="Main navigation"><a href="/">Home</a><div class="nav-item products-menu"><a class="active" href="products.html">Products</a><div class="mega-dropdown" role="menu" aria-label="Products mega menu"><div class="mega-panel"><div class="mega-featured"><a class="mega-product" href="product-detail.html?product=pins"><img src="assets/images/mega-lapel-pins-auburn.jpg" alt="Custom Auburn lapel pin"><span>Lapel Pins</span><small>Custom enamel pins for brands, events and clubs.</small></a><a class="mega-product" href="product-detail.html?product=medals"><img src="assets/images/mega-medals-butterfly.png" alt="Custom butterfly medal with ribbon"><span>Medals</span><small>Colorful award medals with ribbons and finishes.</small></a><a class="mega-product" href="product-detail.html?product=coins"><img src="assets/images/mega-challenge-coin-christmas.jpg" alt="Custom Christmas challenge coin"><span>Challenge Coins</span><small>Detailed coins for recognition and commemorations.</small></a></div><div class="mega-list"><a href="product-detail.html?product=pins">Lapel Pins</a><a href="product-detail.html?product=coins">Challenge Coins</a><a href="product-detail.html?product=medals">Medals</a><a href="product-detail.html?product=keychains">Keychains</a><a href="product-detail.html?product=buckles">Belt Buckles</a><a href="product-detail.html?product=golf-accessories">Golf Ball Markers &amp;Hat Clips</a><a href="product-detail.html?product=bottle-openers">Bottle Openers</a><a href="product-detail.html?product=cufflinks-tieclips">Cufflinks &amp; Tie Clips</a><a href="product-detail.html?product=magnets">Fridge Magnets</a></div><div class="mega-cta"><div><strong>Need a custom product quote?</strong><span>Send logo, quantity and deadline. We reply within 1 business day.</span></div><a class="btn btn-yellow" href="contact.html">Get Free Quote</a></div></div></div></div><a href="custom.html">Custom</a><a href="about.html">About Us</a><a href="blog.html">Blog</a><a href="contact.html">Contact Us</a></nav><div class="nav-actions"><a class="btn btn-primary" href="contact.html">Get Free Quote</a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false">&#9776;</button></div></div></header>

  <main>
    <section class="page-hero products-page-hero">
      <div class="container about-hero-copy">
        <h1>Custom Metal Products</h1>
        <p>We specialize in custom enamel pins, medals, challenge coins, keychains and premium metal gifts. From original designs to mass production, we provide reliable OEM solutions for brands, distributors and organizations worldwide.</p>
      </div>
    </section>

    ${productCategoryNavHtml({ mode: "filter", active: "all" })}

    <section class="product-type-section products-all-section" id="all">
      <div class="container product-type-content">
        <div class="product-type-grid products-all-grid">
          <article class="product-type-card" id="pins" data-product-category="pins"><img src="assets/images/type-pins-soft-enamel.jpg" alt="Green character soft enamel pin set"><h3>Green Character Soft Enamel Pin Set</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=green-character-soft-enamel-pin-set">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-hard-enamel.jpg" alt="Box cat and umbrella cat hard enamel pins"><h3>Box Cat and Umbrella Cat Enamel Pins</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=box-cat-and-umbrella-cat-enamel-pins">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-die-struck.jpg" alt="Antique silver guitar crest enamel pin"><h3>Antique Silver Guitar Crest Enamel Pin</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=antique-silver-guitar-crest-enamel-pin">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="pins"><img src="assets/images/type-pins-printed.jpg" alt="Glitter tour truck printed enamel pin"><h3>Glitter Tour Truck Printed Enamel Pin</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=glitter-tour-truck-printed-enamel-pin">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="coins" data-product-category="coins"><img src="assets/images/type-coins-3d.jpg" alt="3D antique firefighter challenge coins"><h3>3D Antique Firefighter Challenge Coins</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=3d-antique-firefighter-challenge-coins">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="coins"><img src="assets/images/type-coins-double-sided.jpg" alt="Double sided anniversary challenge coin"><h3>Double Sided Anniversary Challenge Coin</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=double-sided-anniversary-challenge-coin">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="coins"><img src="assets/images/type-coins-cut-shape.jpg" alt="Cut shape route map challenge coin"><h3>Cut Shape Route Map Challenge Coin</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=cut-shape-route-map-challenge-coin">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="coins"><img src="assets/images/type-coins-antique.jpg" alt="Antique military squadron challenge coins"><h3>Antique Military Squadron Challenge Coins</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=antique-military-squadron-challenge-coins">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="medals" data-product-category="medals"><img src="assets/images/type-medals-sports.png" alt="Silver basketball sports medal with ribbon"><h3>Silver Basketball Sports Medal with Ribbon</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=silver-basketball-sports-medal-with-ribbon">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="medals"><img src="assets/images/type-medals-3d.png" alt="3D shield logo award medal"><h3>3D Shield Logo Award Medal</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=3d-shield-logo-award-medal">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="medals"><img src="assets/images/type-medals-award.png" alt="Silver race award medal with ribbon"><h3>Silver Race Award Medal with Ribbon</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=silver-race-award-medal-with-ribbon">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="medals"><img src="assets/images/type-medals-ribbon.png" alt="Blue marathon ribbon medal"><h3>Blue Marathon Ribbon Medal</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=blue-marathon-ribbon-medal">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="keychains" data-product-category="keychains"><img src="assets/images/type-keychains-metal.jpg" alt="Colorful flower metal keychains"><h3>Colorful Flower Metal Keychains</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=colorful-flower-metal-keychains">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="keychains"><img src="assets/images/type-keychains-enamel.jpg" alt="Palm island enamel keychain"><h3>Palm Island Enamel Keychain</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=palm-island-enamel-keychain">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="keychains"><img src="assets/images/type-keychains-opener.jpg" alt="Round school logo keychain"><h3>Round School Logo Keychain</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=round-school-logo-bottle-opener-keychain">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="keychains"><img src="assets/images/type-keychains-spinner.jpg" alt="Travel charm spinner keychain"><h3>Travel Charm Spinner Keychain</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=travel-charm-spinner-keychain">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="buckles" data-product-category="buckles"><img src="assets/images/type-buckles-western.jpg" alt="Western skull relief belt buckle"><h3>Western Skull Relief Belt Buckle</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=western-skull-relief-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="buckles"><img src="assets/images/type-buckles-logo.jpg" alt="Oval relief logo metal belt buckle"><h3>Oval Relief Logo Metal Belt Buckle</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=oval-relief-logo-metal-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="buckles"><img src="assets/images/type-buckles-antique.jpg" alt="Antique silver rectangle logo belt buckle"><h3>Antique Silver Rectangle Logo Belt Buckle</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=antique-silver-rectangle-logo-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="buckles"><img src="assets/images/type-buckles-enamel.jpg" alt="Oval club logo enamel belt buckle"><h3>Oval Club Logo Enamel Belt Buckle</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=oval-club-logo-enamel-belt-buckle">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="golf-accessories" data-product-category="golf-accessories"><img src="assets/images/type-golf-ball-marker.jpg" alt="Antique golf club divot tool ball marker"><h3>Antique Golf Club Divot Tool Ball Marker</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=antique-golf-club-divot-tool-ball-marker">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="golf-accessories"><img src="assets/images/type-golf-hat-clip.jpg" alt="Avocado golf hat clip ball marker"><h3>Avocado Golf Hat Clip Ball Marker</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=avocado-golf-hat-clip-ball-marker">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="golf-accessories"><img src="assets/images/type-golf-divot-tool.jpg" alt="Color logo golf divot tool set"><h3>Color Logo Golf Divot Tool Set</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=color-logo-golf-divot-tool-set">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="bottle-openers" data-product-category="bottle-openers"><img src="assets/images/type-openers-coin.jpg" alt="Playing card metal bottle opener"><h3>Playing Card Metal Bottle Opener</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=playing-card-metal-bottle-opener">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="bottle-openers"><img src="assets/images/type-openers-keychain.jpg" alt="Skull coin keychain bottle opener"><h3>Skull Coin Keychain Bottle Opener</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=skull-coin-keychain-bottle-opener">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="cufflinks-tieclips" data-product-category="cufflinks-tieclips"><img src="assets/images/type-cufflinks-metal.jpg" alt="Blue carbon fiber metal cufflinks"><h3>Blue Carbon Fiber Metal Cufflinks</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=blue-carbon-fiber-metal-cufflinks">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="cufflinks-tieclips"><img src="assets/images/type-cufflinks-enamel.jpg" alt="Color plated metal tie clips"><h3>Color Plated Metal Tie Clips</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=color-plated-metal-tie-clips">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="cufflinks-tieclips"><img src="assets/images/type-tie-clips-logo.jpg" alt="Black skull logo cufflinks"><h3>Black Skull Logo Cufflinks</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=black-skull-logo-cufflinks">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>

          <article class="product-type-card" id="magnets" data-product-category="magnets"><img src="assets/images/type-magnets-enamel.png" alt="Ornate building enamel fridge magnet"><h3>Ornate Building Enamel Fridge Magnet</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=ornate-building-enamel-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="magnets"><img src="assets/images/type-magnets-3d.png" alt="Ferris wheel 3D metal fridge magnet"><h3>Ferris Wheel 3D Metal Fridge Magnet</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=ferris-wheel-3d-metal-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="magnets"><img src="assets/images/type-magnets-soft-pvc.png" alt="Cartoon character soft fridge magnet"><h3>Cartoon Character Soft Fridge Magnet</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=cartoon-character-soft-pvc-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
          <article class="product-type-card" data-product-category="magnets"><img src="assets/images/type-magnets-souvenir.png" alt="City landmark souvenir fridge magnet"><h3>City Landmark Souvenir Fridge Magnet</h3><div class="product-type-actions"><a class="product-type-btn product-type-btn-outline" href="product-item.html?item=city-landmark-souvenir-fridge-magnet">View More</a><a class="product-type-btn product-type-btn-primary" href="contact.html">GET QUOTE NOW</a></div></article>
        </div>
      </div>
    </section>

  </main>

  <footer class="site-footer">
    <div class="container footer-grid">
      <div class="footer-logo-wrap"><img class="footer-logo" src="assets/images/logo.png" alt="Unique Pin logo"></div>
      <div><h4>Products</h4><a href="products.html">Custom Enamel Pins</a><a href="products.html">Custom Medals</a><a href="products.html">Challenge Coins</a><a href="products.html">Keychains</a></div>
      <div><h4>Get Started</h4><a href="custom.html">Custom</a><a href="about.html">About Us</a><a href="blog.html">Blog</a><a href="faq.html">FAQ</a></div>
      <div><h4>Contact</h4><a href="mailto:ceo@chinauniquepin.com">Email: ceo@chinauniquepin.com</a><a href="tel:+86076022831989">Phone: +86 0760 22831989</a><p>Building A, 1st Floor, No. 7 Xingyu Road, Xiaolan Town, Zhongshan City, Guangdong, China</p></div>
    </div>
    <div class="container footer-bottom"><span>&copy; 2026 Unique Pin. All rights reserved.</span><span class="footer-social"><a class="footer-social-facebook" href="https://www.facebook.com/profile.php?id=61583070933333&locale=zh_CN" aria-label="Facebook" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8.5h2.2V5.1c-.4-.1-1.7-.2-3.2-.2-3.2 0-5.3 1.9-5.3 5.5v3.1H4.2v3.8h3.5V24h4.3v-6.7h3.3l.6-3.8H12v-2.7c0-1.1.3-2.3 2-2.3Z"></path></svg></a><a class="footer-social-instagram" href="https://www.instagram.com/uniquepin/" aria-label="Instagram" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 2h9.6A5.2 5.2 0 0 1 22 7.2v9.6a5.2 5.2 0 0 1-5.2 5.2H7.2A5.2 5.2 0 0 1 2 16.8V7.2A5.2 5.2 0 0 1 7.2 2Zm0 2A3.2 3.2 0 0 0 4 7.2v9.6A3.2 3.2 0 0 0 7.2 20h9.6a3.2 3.2 0 0 0 3.2-3.2V7.2A3.2 3.2 0 0 0 16.8 4H7.2Zm4.8 3.7A4.3 4.3 0 1 1 7.7 12 4.3 4.3 0 0 1 12 7.7Zm0 2A2.3 2.3 0 1 0 14.3 12 2.3 2.3 0 0 0 12 9.7Zm4.6-3.2a1 1 0 1 1-1 1 1 1 0 0 1 1-1Z"></path></svg></a><a class="footer-social-youtube" href="https://www.youtube.com/@CustompinUnique" aria-label="YouTube" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 7.1a3 3 0 0 0-2.1-2.1C17.6 4.5 12 4.5 12 4.5s-5.6 0-7.5.5a3 3 0 0 0-2.1 2.1A31.2 31.2 0 0 0 2 12a31.2 31.2 0 0 0 .4 4.9A3 3 0 0 0 4.5 19c1.9.5 7.5.5 7.5.5s5.6 0 7.5-.5a3 3 0 0 0 2.1-2.1A31.2 31.2 0 0 0 22 12a31.2 31.2 0 0 0-.4-4.9ZM10 15.5v-7l6 3.5-6 3.5Z"></path></svg></a></span></div>
  </footer>`;

export default function Page() {
  return <StaticPage html={html} />;
}
